apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-hello-world
  labels:
    app: springboot-hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-hello-world
  template:
    metadata:
      labels:
        app: springboot-hello-world
    spec:
      containers:
      - name: app
        image: shashidharreddy217/springboot-hello-world:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 30
