apiVersion: v1
kind: Service
metadata:
  name: springboot-hello-world-svc
spec:
  type: NodePort
  selector:
    app: springboot-hello-world
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081
