apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: springboot-hello-world-sm
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: springboot-hello-world
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
      scheme: http
